name: shell-injection-issue-demo

on: issues

jobs:
  shell-injection:
    name: shell injection simple demo
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: run tests
      id: test
      run: |
        issue_title="${{ github.event.issue.title }}"
        artifact_name="`echo $issue_title | tr -d [:blank:]`-test-output.json"
        echo $artifact_name
        echo ::set-output name=ISSUE_TITLE::"$(echo $issue_title)"
        echo ::set-output name=ARTIFACT_NAME::"$(echo $artifact_name)"
        ./test > $artifact_name
    - name: upload test artifact to repository
      run: |
        artifact_name="${{ steps.test.outputs.ARTIFACT_NAME }}"
        echo $artifact_name
        content="`cat $artifact_name | openssl base64 | tr -d '\n'`"
        echo $content
        curl --request PUT \
          --url https://api.github.com/repos/${{ github.repository }}/contents/test_artifacts/$artifact_name \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'Accept: application/vnd.github.v3+json' \
          --data "{\"message\":\"upload test artifact\", \"content\":\"$content\"}"
    - name: attach test artifact to issue
      run: |
        artifact_name="${{ steps.test.outputs.ARTIFACT_NAME }}"
        echo $artifact_name
        curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --data "{\"body\": \"https://github.com/${{ github.repository }}/blob/main/test_artifacts/$artifact_name\"}"
      
