name: shell-injection-issue-demo

on: issues

jobs:
  shell-injection:
    name: shell injection simple demo
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: run tests
      id: test
      run: |
        issue_title="${{ github.event.issue.title }}"
        artifact_name="`echo $issue_title | tr -d [:blank:]`-test-output.json"
        echo $artifact_name
        echo '::set-output name=ISSUE_TITLE::`echo $issue_title`'
        echo '::set-output name=ARTIFACT_NAME::`echo $artifact_name`'
        ./test > $artifact_name
    - name: upload test artifact to repository
      run: |
        artifact_name="${{ steps.test.outputs.ARTIFACT_NAME }}"
        echo $artifact_name
        content="`cat $artifact_name`"
        curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/contents/$artifact_name \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --data '{ \
              "message": "upload test artifact", \
              "content": "`cat $artifact_name | openssl base64`" \
            }'
    - name: attach test artifact to issue
      run: |
        curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --data '{ \
              "body": "${{ steps.test.outputs.ARTIFACT_NAME }}" \
            }'
      
